# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/takagilab/Desktop/blink/blink.cache/wt [current_project]
set_property parent.project_path C:/Users/takagilab/Desktop/blink/blink.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib C:/Users/takagilab/Desktop/blink/blink.srcs/sources_1/imports/Desktop/blink.v
read_xdc C:/Users/takagilab/Desktop/blink/blink.srcs/constrs_1/new/blink.xdc
set_property used_in_implementation false [get_files C:/Users/takagilab/Desktop/blink/blink.srcs/constrs_1/new/blink.xdc]

synth_design -top blink -part xc7z020clg484-1
write_checkpoint -noxdef blink.dcp
catch { report_utilization -file blink_utilization_synth.rpt -pb blink_utilization_synth.pb }
